// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzmvajjkrzvafrdxixnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6bXZhamprcnp2YWZyZHhpeG5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM3Nzg4MzgsImV4cCI6MjA0OTM1NDgzOH0.A8SFzg445TBHeSyyl5bjpMofo3fsToibP9m46zR2iPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);